/* The sign-in screen's own art, as PNG bytes (ui_art.c, generated by tools/make_ui_art.py from
 * assets/ui/). */
#pragma once

#include <stddef.h>

typedef struct UiArt
{
    const char* name; /* "button", "button_on" */
    const unsigned char* png;
    size_t size;
} UiArt;

/* Ends with a NULL name. */
extern const UiArt ui_art[];
/* The pills: their size in the images, and the room around them (the shadow) on every side. */
extern const int ui_art_pill_w, ui_art_pill_h, ui_art_pad;
