"""The sign-in screen's own art (host/signin.c): high-resolution button pills, drawn here rather than
cut from the game's 15-texel ones, which blur when scaled to a modern window.

  python3 tools/make_ui_art.py      writes assets/ui/*.png and host/ui_art.c (the PNGs as bytes)

Each pill is drawn at 4x and filtered down: a vertical gradient, a thin border, a gloss over its upper
half and a soft shadow below, with PAD pixels of room around it for the shadow. The screen draws it
in three slices - two round caps (as wide as the pill is tall, halved) and a middle that stretches.
Needs Pillow."""
import os
import sys

from PIL import Image, ImageChops, ImageDraw, ImageFilter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
W, H, PAD = 384, 96, 16  # the pill, and the room around it (the image is W + 2 PAD by H + 2 PAD)
SS = 4                   # supersampling

STYLES = {
    # name: gradient top, gradient bottom, border, gloss alpha
    'button': ((255, 255, 255), (214, 219, 228), (120, 130, 152), 150),
    'button_on': ((255, 246, 215), (233, 190, 108), (164, 120, 44), 170),
}


def pill_mask(w, h, inset=0):
    m = Image.new('L', (w, h), 0)
    ImageDraw.Draw(m).rounded_rectangle((inset, inset, w - 1 - inset, h - 1 - inset), radius=(h - 2 * inset) // 2, fill=255)
    return m


def gradient(w, h, top, bottom):
    g = Image.new('RGB', (1, h))
    for y in range(h):
        t = y / (h - 1)
        g.putpixel((0, y), tuple(round(a + (b - a) * t) for a, b in zip(top, bottom)))
    return g.resize((w, h))


def pill(top, bottom, border, gloss):
    w, h, pad = W * SS, H * SS, PAD * SS
    out = Image.new('RGBA', (w + 2 * pad, h + 2 * pad), (0, 0, 0, 0))
    # the shadow: the pill's shape, dark, a little low, blurred
    shadow = Image.new('L', out.size, 0)
    shadow.paste(pill_mask(w, h), (pad, pad + 3 * SS))
    shadow = shadow.filter(ImageFilter.GaussianBlur(5 * SS)).point(lambda v: v * 90 // 255)
    out.paste(Image.new('RGBA', out.size, (10, 16, 36, 255)), (0, 0), shadow)
    # the border, then the body inside it
    edge = 2 * SS
    body = Image.new('RGBA', (w, h), border + (255,))
    inner = gradient(w, h, top, bottom).convert('RGBA')
    body.paste(inner, (0, 0), pill_mask(w, h, edge))
    # the gloss: a lighter band over the upper half, fading down
    band = Image.new('L', (w, h), 0)
    for y in range(h // 2):
        ImageDraw.Draw(band).line((0, y + edge, w, y + edge), fill=round(gloss * (1 - y / (h / 2)) ** 1.6))
    band = ImageChops.multiply(band, pill_mask(w, h, edge + SS))
    body.paste(Image.new('RGBA', (w, h), (255, 255, 255, 255)), (0, 0), band)
    out.paste(body, (pad, pad), pill_mask(w, h))
    return out.resize(((W + 2 * PAD), (H + 2 * PAD)), Image.LANCZOS)


def main():
    art = os.path.join(ROOT, 'assets', 'ui')
    os.makedirs(art, exist_ok=True)
    blobs = []
    for name, style in STYLES.items():
        path = os.path.join(art, name + '.png')
        pill(*style).save(path, optimize=True)
        with open(path, 'rb') as f:
            blobs.append((name, f.read()))
        print('wrote', os.path.relpath(path, ROOT))
    with open(os.path.join(ROOT, 'host', 'ui_art.c'), 'w') as f:
        f.write('/* Generated by tools/make_ui_art.py from assets/ui/: do not edit. */\n#include "ui_art.h"\n\n')
        for name, data in blobs:
            f.write('static const unsigned char %s_png[%d] = {\n' % (name, len(data)))
            for i in range(0, len(data), 20):
                f.write('    ' + ', '.join('%d' % b for b in data[i:i + 20]) + ',\n')
            f.write('};\n\n')
        f.write('const UiArt ui_art[] = {\n')
        for name, data in blobs:
            f.write('    { "%s", %s_png, sizeof %s_png },\n' % (name, name, name))
        f.write('    { 0, 0, 0 },\n};\n')
        f.write('const int ui_art_pill_w = %d, ui_art_pill_h = %d, ui_art_pad = %d;\n' % (W, H, PAD))
    print('wrote host/ui_art.c')
    return 0


if __name__ == '__main__':
    sys.exit(main())
